name: Deploy to Firebase Hosting - Dev
"on":
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build_and_deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: yarn install --frozen-lockfile && npm run build:dev
        env:
          CI: false

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.SECRETJSON_DEV }}"
          channelId: live
          projectId: rayon-gcp-starter
          target: dev
